import {

    useEffect,
    useState,
  
  } from "react";
  
  import {
  
    getReports,
    generateReport,
    downloadReport,
  
    type Report,
  
  } from "../api/reports";
  
  export default function Reports() {
  
    const [reports, setReports] =
      useState<Report[]>([]);
  
    const [loading, setLoading] =
      useState(true);
  
    // ===================================================
    // LOAD REPORTS
    // ===================================================
  
    async function loadReports() {
  
      try {
  
        const data =
          await getReports();
  
        setReports(data);
  
      } catch (error) {
  
        console.error(error);
  
      } finally {
  
        setLoading(false);
      }
    }
  
    useEffect(() => {
  
      loadReports();
  
    }, []);
  
    // ===================================================
    // GENERATE NEW REPORT
    // ===================================================
  
    async function handleGenerate() {
  
      await generateReport();
  
      setTimeout(() => {
  
        loadReports();
  
      }, 2000);
    }
  
    // ===================================================
    // LOADING
    // ===================================================
  
    if (loading) {
  
      return (
  
        <div className="p-8">
  
          Loading reports...
  
        </div>
      );
    }
  
    // ===================================================
    // UI
    // ===================================================
  
    return (
  
      <div className="p-8 bg-gray-50 min-h-screen">
  
        {/* ========================================== */}
        {/* HEADER */}
        {/* ========================================== */}
  
        <div className="flex items-center justify-between mb-8">
  
          <div>
  
            <h1 className="text-4xl font-bold text-gray-900">
  
              Reports Dashboard
  
            </h1>
  
            <p className="text-gray-500 mt-2">
  
              Weekly outbreak intelligence reports
  
            </p>
  
          </div>
  
          <button
  
            onClick={handleGenerate}
  
            className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-xl font-semibold shadow-lg transition-all"
          >
  
            Generate Weekly Report
  
          </button>
        </div>
  
        {/* ========================================== */}
        {/* SUMMARY CARDS */}
        {/* ========================================== */}
  
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
  
          {/* TOTAL */}
  
          <div className="bg-white rounded-2xl p-6 shadow-md border">
  
            <p className="text-gray-500">
  
              Total Reports
  
            </p>
  
            <h2 className="text-4xl font-bold mt-2">
  
              {reports.length}
  
            </h2>
          </div>
  
          {/* WEEKLY */}
  
          <div className="bg-indigo-50 rounded-2xl p-6 shadow-md border border-indigo-100">
  
            <p className="text-indigo-600">
  
              Weekly Reports
  
            </p>
  
            <h2 className="text-4xl font-bold mt-2 text-indigo-700">
  
              {
  
                reports.filter(
  
                  r =>
                    r.report_type ===
                    "weekly"
                ).length
  
              }
  
            </h2>
          </div>
  
          {/* LATEST */}
  
          <div className="bg-green-50 rounded-2xl p-6 shadow-md border border-green-100">
  
            <p className="text-green-600">
  
              Latest Report
  
            </p>
  
            <h2 className="text-lg font-bold mt-3 text-green-700">
  
              {
  
                reports[0]
                  ?.generated_at
                  ?.split("T")[0]
              }
  
            </h2>
          </div>
        </div>
  
        {/* ========================================== */}
        {/* REPORT HISTORY */}
        {/* ========================================== */}
  
        <div className="bg-white rounded-2xl shadow-md border overflow-hidden">
  
          <div className="p-6 border-b">
  
            <h2 className="text-2xl font-bold">
  
              Report History
  
            </h2>
          </div>
  
          <div className="overflow-x-auto">
  
            <table className="w-full">
  
              <thead className="bg-gray-100">
  
                <tr>
  
                  <th className="text-left p-4">
  
                    Report
  
                  </th>
  
                  <th className="text-left p-4">
  
                    Type
  
                  </th>
  
                  <th className="text-left p-4">
  
                    Generated
  
                  </th>
  
                  <th className="text-left p-4">
  
                    Generated By
  
                  </th>
  
                  <th className="text-left p-4">
  
                    Download
  
                  </th>
  
                </tr>
              </thead>
  
              <tbody>
  
                {reports.map((report) => (
  
                  <tr
  
                    key={report.id}
  
                    className="border-t hover:bg-gray-50"
                  >
  
                    <td className="p-4 font-medium">
  
                      {report.filename}
  
                    </td>
  
                    <td className="p-4 capitalize">
  
                      {report.report_type}
  
                    </td>
  
                    <td className="p-4">
  
                      {
  
                        report.generated_at
                          .split("T")[0]
                      }
  
                    </td>
  
                    <td className="p-4">
  
                      {report.generated_by}
  
                    </td>
  
                    <td className="p-4">
  
                      <button
  
                        onClick={() =>
                          downloadReport(
                            report.id
                          )
                        }
  
                        className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg"
                      >
  
                        Download PDF
  
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
  
          </div>
        </div>
      </div>
    );
  }